//
//  User.h
//  Toast
//
//  Created by Thomas Beatty on 6/18/12.
//  Copyright (c) 2012 Strabo. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

@class Album;

/**
 An object to hold information about a user.
 
 Everytime a user logs in, Core Data should be checked for the existance of a related user object and a new one created if necessary. If one exists, a duplicate should not be created.
 */
@interface User : NSManagedObject

/**
 The strabo-specific user ID generated by the server during login.
 */
@property (nonatomic, retain) NSNumber * userID;

/**
 The albums associated with a user.
 
 Albums must be accessed throughout the application by determining the set of albums owned by the current user through this object. Albums should never be retrieved directly through the core data managed object context to prevent unauthorized users from seeing albums that they do not own.
 */
@property (nonatomic, retain) NSSet *albums;

@end

@interface User (CoreDataGeneratedAccessors)

- (void)addAlbumsObject:(Album *)value;
- (void)removeAlbumsObject:(Album *)value;
- (void)addAlbums:(NSSet *)values;
- (void)removeAlbums:(NSSet *)values;

@end
